### ISSUE TITLE
'Reservoir_update' object has no attribute 'new_task'

### ISSUE THREAD

**Issue by weixia1187** [vimar-gu/SSD#1]
line 105 in buffer.py, self.update_method.new_task(self.num_classes, labels)
'Reservoir_update' object has no attribute 'new_task'
  File "D:\workspace\SSD-main\utils\buffer\buffer.py", line 105, in new_condense_task
    self.update_method.new_task(self.num_classes, labels)
  File "D:\workspace\SSD-main\agents\summarize.py", line 39, in train_learner
    self.buffer.new_condense_task(labels)
  File "D:\workspace\SSD-main\experiment\run.py", line 49, in multiple_run
    agent.train_learner(x_train, y_train, labels=labels)
  File "D:\workspace\SSD-main\general_main.py", line 27, in main
    multiple_run(args, store=args.store, save_path=args.save_path)
  File "D:\workspace\SSD-main\general_main.py", line 208, in <module>
    main(args)
AttributeError: 'Reservoir_update' object has no attribute 'new_task'

**Comment by weixia1187** [comment]
Among all the update_methods, only 'summarize' has attribute  'new_task'. So, this is a bug. If you choose other update_methods, there will be this error.

**Comment by vimar-gu** [comment]
Thanks for the feedback!

As only 'summarize' requires to run the `new_condense_task` function, I didn't maintain the compability for other update methods. 

I will fix the bug afterwards.

**Comment by vimar-gu** [comment]
If you use other update methods, you can modify the `--agent SSCR` to `--agent SCR` to avoid this error.
