### ISSUE TITLE
Error during training

### ISSUE THREAD

**Issue by weixia1187** [vimar-gu/SSD#2]
During my training process, there is an error occurred in line 171 of  base.py, and it shows like this :Dimension out of range (expected to be in range of [-1, 0], but got 1).  Should I turn _, pred_label = dists.min(1) to _, pred_label = dists.unsqueeze(0).min(1)?

**Comment by vimar-gu** [comment]
Can you check the shape of the `dists` variable?

**Comment by weixia1187** [comment]
the shape of the dists is torch.Size([128])

**Comment by vimar-gu** [comment]
The shape of `dists` is supposed to be (batch_size, num_classes). 

Can you further check if the num_classes argument setting is correct?

**Comment by weixia1187** [comment]
i think there might be something wrong with the variable means, the shape of means is 128*160*1. I can't find num_classes argument, I only find num_classes_per_task argument in general_main.py.

**Comment by vimar-gu** [comment]
There are comments in each line suggesting the shape of variables. 
You can run pdb and check in which line the shape is no longer what it is supposed to be. 

Also can you provide the running command for replicating the problems?

**Comment by weixia1187** [comment]
python general_main.py --data cifar10 --cl_type nc --agent SSCR --retrieve random --update summarize --mem_size 1000 --images_per_class 10 --head mlp --temp 0.07 --eps_mem_batch 100 --lr_img 4e-3 --summarize_interval 6 --queue_size 64 --mem_weight 1 --num_runs 10

**Comment by vimar-gu** [comment]
You are separating CIFAR-10 into 10 tasks where each task only contains 1 class. 
So definitely you cannot obtain the correct `dists` shape. 

There's supposed to be class separation at the beginning of the code output. 

You can read the arguments provided in the `general_main.py` and change the `num_tasks` argument to have correct dataset splts.

**Comment by weixia1187** [comment]
I see. Thank you very much for your patience in answering my questions. Really appreciate on it。
