### ISSUE TITLE
About comparison experiment

### ISSUE THREAD

**Issue by ray-ruisun** [vimar-gu/SSD#3]
Dear Authors,

Is it possible to know how to run (correct starting parameters) the comparison experiments that this work supported?
![image](https://github.com/vimar-gu/SSD/assets/19859583/87ed0130-2da1-40cc-ad02-191c4643cc18)

Thanks,
Ray

**Comment by vimar-gu** [comment]
Hi, you can refer to the [online-continual-learning](https://github.com/RaptorMai/online-continual-learning) repo for running commands. Directly using our repo to run the compared methods might encounter some incompatibility. So using the original repo can be a better choice.

**Comment by ray-ruisun** [comment]
This is helpful, thank you very much
